/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unimport-loader
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Else: typeof import('react-if-lite').Else
  const Fragment: typeof import('react').Fragment
  const If: typeof import('react-if-lite').If
  const ServiceLoaded: typeof import('./src/components/service-loaded').ServiceLoaded
  const Suspense: typeof import('react').Suspense
  const Then: typeof import('react-if-lite').Then
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createPortal: typeof import('react-dom').createPortal
  const createRef: typeof import('react').createRef
  const defineStore: typeof import('valtio-define').defineStore
  const flushSync: typeof import('react-dom').flushSync
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const preconnect: typeof import('react-dom').preconnect
  const prefetchDNS: typeof import('react-dom').prefetchDNS
  const preinit: typeof import('react-dom').preinit
  const preinitModule: typeof import('react-dom').preinitModule
  const preload: typeof import('react-dom').preload
  const preloadModule: typeof import('react-dom').preloadModule
  const queryClient: typeof import('./src/config/client').queryClient
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useFormStatus: typeof import('react-dom').useFormStatus
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInfiniteQuery: typeof import('@tanstack/react-query').useInfiniteQuery
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useMutation: typeof import('@tanstack/react-query').useMutation
  const useOptimistic: typeof import('react').useOptimistic
  const useQuery: typeof import('@tanstack/react-query').useQuery
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useStore: typeof import('valtio-define').useStore
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
