shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*
patchedDependencies:
  bumpp: patches/bumpp.patch

ignoredBuiltDependencies:
  - electron

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@tailwindcss/oxide'
  - esbuild
