shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*
overrides:
  "@types/react": "^19.2.9"
  "@types/react-dom": "^19.2.3"
patchedDependencies:
  bumpp: patches/bumpp.patch

ignoredBuiltDependencies:
  - electron

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@tailwindcss/oxide'
  - esbuild
