shellEmulator: true
trustPolicy: no-downgrade

patchedDependencies:
  bumpp: patches/bumpp.patch

ignoredBuiltDependencies:
  - electron

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@tailwindcss/oxide'
  - esbuild
