/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Else: typeof import('react-if-lite').Else
  const Fragment: typeof import('react').Fragment
  const IconArrowUp: typeof import('../components/icons').IconArrowUp
  const IconChat: typeof import('../components/icons').IconChat
  const IconChevronDown: typeof import('../components/icons').IconChevronDown
  const IconCompass: typeof import('../components/icons').IconCompass
  const IconCopy: typeof import('../components/icons').IconCopy
  const IconEllipsis: typeof import('../components/icons').IconEllipsis
  const IconLibrary: typeof import('../components/icons').IconLibrary
  const IconPaperclip: typeof import('../components/icons').IconPaperclip
  const IconPlus: typeof import('../components/icons').IconPlus
  const IconSearch: typeof import('../components/icons').IconSearch
  const IconShare: typeof import('../components/icons').IconShare
  const If: typeof import('react-if-lite').If
  const Link: typeof import('react-router-dom').Link
  const Main: typeof import('../components/main').Main
  const NavLink: typeof import('react-router-dom').NavLink
  const Navbar: typeof import('../components/navbar').Navbar
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const Provider: typeof import('../components/provider').Provider
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const ServiceLoaded: typeof import('../components/service-loaded').ServiceLoaded
  const Sidebar: typeof import('../components/sidebar').Sidebar
  const Suspense: typeof import('react').Suspense
  const Then: typeof import('react-if-lite').Then
  const Webview: typeof import('../components/webview').Webview
  const WebviewContainer: typeof import('../components/webview').WebviewContainer
  const baseProps: typeof import('../components/icons').baseProps
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const clsx: typeof import('clsx').clsx
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const db: typeof import('../database/index').db
  const forwardRef: typeof import('react').forwardRef
  const layouts: typeof import('../layout/index').layouts
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const queryClient: typeof import('../config/client').queryClient
  const startTransition: typeof import('react').startTransition
  const storage: typeof import('../config/storage').storage
  const tauriStorageDriver: typeof import('../config/storage.driver').tauriStorageDriver
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useObserver: typeof import('../components/webview.hooks').useObserver
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const useWebview: typeof import('../components/webview.hooks').useWebview
  const useWebviewResizeToElement: typeof import('../components/webview.hooks').useWebviewResizeToElement
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Generated, Timestamp, DB } from '../database/types'
  import('../database/types')
  // @ts-ignore
  export type { TauriStorageDriverOptions } from '../config/storage.driver'
  import('../config/storage.driver')
  // @ts-ignore
  export type { WebviewProps } from '../components/webview'
  import('../components/webview')
}
