/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Alimail: typeof import('../components/icons').Alimail
  const AlimailIcon: typeof import('../components/icons').AlimailIcon
  const ClickupIcon: typeof import('../components/icons').ClickupIcon
  const DEFAULT_N8N_LOGIN_DATA: typeof import('../config/constants').DEFAULT_N8N_LOGIN_DATA
  const DEFAULT_N8N_REGISTER_DATA: typeof import('../config/constants').DEFAULT_N8N_REGISTER_DATA
  const DeleteReportModal: typeof import('../components/delete-report-modal').DeleteReportModal
  const DiscordIcon: typeof import('../components/icons').DiscordIcon
  const Fragment: typeof import('react').Fragment
  const GitIcon: typeof import('../components/icons').GitIcon
  const GitSourceForm: typeof import('../components/souce-git-form').GitSourceForm
  const GithubIcon: typeof import('../components/icons').GithubIcon
  const GmailIcon: typeof import('../components/icons').GmailIcon
  const HeartFilledIcon: typeof import('../components/icons').HeartFilledIcon
  const Initialize: typeof import('../components/initialize').Initialize
  const Link: typeof import('react-router-dom').Link
  const Logo: typeof import('../components/icons').Logo
  const MoonFilledIcon: typeof import('../components/icons').MoonFilledIcon
  const N8N_API_URL: typeof import('../config/constants').N8N_API_URL
  const N8N_LOGIN_DATA: typeof import('../config/constants').N8N_LOGIN_DATA
  const N8N_REGISTER_DATA: typeof import('../config/constants').N8N_REGISTER_DATA
  const NavLink: typeof import('react-router-dom').NavLink
  const Navbar: typeof import('../layouts/components/navbar').Navbar
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const ReportEditor: typeof import('../components/report-editor').ReportEditor
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const SearchIcon: typeof import('../components/icons').SearchIcon
  const SettingAboutCard: typeof import('../ui/setting-about-card').SettingAboutCard
  const SettingOtherConfig: typeof import('../ui/setting-other-config').SettingOtherConfig
  const SettingUserInterfaceCard: typeof import('../ui/setting-user-interface-card').SettingUserInterfaceCard
  const SlackIcon: typeof import('../components/icons').SlackIcon
  const SourceGitForm: typeof import('../components/souce-git-form').SourceGitForm
  const SourceIcon: typeof import('../components/source-icon').SourceIcon
  const SourceItem: typeof import('../components/source-item').SourceItem
  const SourceItemCard: typeof import('../components/source-item').SourceItemCard
  const SourceSelect: typeof import('../components/source-select').SourceSelect
  const SunFilledIcon: typeof import('../components/icons').SunFilledIcon
  const Suspense: typeof import('react').Suspense
  const ThemeSwitch: typeof import('../components/theme-switch').ThemeSwitch
  const Titlebar: typeof import('../components/titlebar').Titlebar
  const TrendCard: typeof import('../components/trend-card').TrendCard
  const TwitterIcon: typeof import('../components/icons').TwitterIcon
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const collectDailyClickup: typeof import('../services/collect-clickup').collectDailyClickup
  const collectDailyGit: typeof import('../services/collect-git').collectDailyGit
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const createReport: typeof import('../utils/mock-db').createReport
  const createSource: typeof import('../utils/mock-db').createSource
  const db: typeof import('../config/db').db
  const db_p: typeof import('../config/db').db_p
  const db_promise: typeof import('../config/db').db_promise
  const deleteReport: typeof import('../utils/mock-db').deleteReport
  const forwardRef: typeof import('react').forwardRef
  const getAllDatabaseItems: typeof import('../utils/mock-db').getAllDatabaseItems
  const getAllReports: typeof import('../utils/mock-db').getAllReports
  const getDatabaseItemById: typeof import('../utils/mock-db').getDatabaseItemById
  const getKysely: typeof import('../config/db').getKysely
  const getReportById: typeof import('../utils/mock-db').getReportById
  const getSetting: typeof import('../utils/settings-store').getSetting
  const getSettings: typeof import('../utils/settings-store').getSettings
  const getSources: typeof import('../utils/mock-db').getSources
  const iconMap: typeof import('../components/source-icon').iconMap
  const invokeCollectClickup: typeof import('../services/invoke-collect-clickup').invokeCollectClickup
  const invokeCollectGit: typeof import('../services/invoke-collect-git').invokeCollectGit
  const isExistsIndex: typeof import('../utils/db').isExistsIndex
  const isExistsTable: typeof import('../utils/db').isExistsTable
  const layouts: typeof import('../layouts/index').layouts
  const lazy: typeof import('react').lazy
  const loginN8nUser: typeof import('../apis/index').loginN8nUser
  const memo: typeof import('react').memo
  const params: typeof import('../services/post-n8n-workflow.params.mock').params
  const postN8nApiKey: typeof import('../services/post-n8n-api-key').postN8nApiKey
  const postN8nLogin: typeof import('../services/post-n8n-login').postN8nLogin
  const postN8nRegister: typeof import('../services/post-n8n-register').postN8nRegister
  const postN8nWorkflow: typeof import('../services/post-n8n-workflow').postN8nWorkflow
  const postN8nWorkflowParamsMock: typeof import('../services/post-n8n-workflow.mock').postN8nWorkflowParamsMock
  const postN8nWorkflowResultMock: typeof import('../services/post-n8n-workflow.mock').postN8nWorkflowResultMock
  const queryClient: typeof import('../config/client').queryClient
  const registerN8N: typeof import('../apis/index').registerN8N
  const registerN8n: typeof import('../apis/index').registerN8n
  const registerN8nUser: typeof import('../apis/index').registerN8nUser
  const saveSettings: typeof import('../utils/settings-store').saveSettings
  const searchDatabaseItems: typeof import('../utils/mock-db').searchDatabaseItems
  const searchReports: typeof import('../utils/mock-db').searchReports
  const setSetting: typeof import('../utils/settings-store').setSetting
  const settingsStore: typeof import('../config/store').settingsStore
  const siteConfig: typeof import('../config/site').siteConfig
  const sourceOptions: typeof import('../config/options').sourceOptions
  const sql_createRecord: typeof import('../services/sql-record-create').sql_createRecord
  const sql_createReport: typeof import('../services/sql-report-create').sql_createReport
  const sql_createSource: typeof import('../services/sql-source-create').sql_createSource
  const sql_deleteRecord: typeof import('../services/sql-record-delete').sql_deleteRecord
  const sql_deleteReport: typeof import('../services/sql-report-delete').sql_deleteReport
  const sql_deleteSource: typeof import('../services/sql-source-delete').sql_deleteSource
  const sql_isExistsIndex: typeof import('../services/sql-is-exists-index').sql_isExistsIndex
  const sql_isExistsTable: typeof import('../services/sql-is-exists-tables').sql_isExistsTable
  const sql_queryRecordById: typeof import('../services/sql-record-query_id').sql_queryRecordById
  const sql_queryRecords: typeof import('../services/sql-record-query').sql_queryRecords
  const sql_queryReportById: typeof import('../services/sql-report-query_id').sql_queryReportById
  const sql_queryReports: typeof import('../services/sql-report-query').sql_queryReports
  const sql_querySourceById: typeof import('../services/sql-source-query_id').sql_querySourceById
  const sql_querySources: typeof import('../services/sql-source-query').sql_querySources
  const sql_searchReports: typeof import('../services/sql-search-reports').sql_searchReports
  const sql_updateRecord: typeof import('../services/sql-record-update').sql_updateRecord
  const sql_updateReport: typeof import('../services/sql-report-update').sql_updateReport
  const startTransition: typeof import('react').startTransition
  const store: typeof import('../store/index').store
  const subtitle: typeof import('../components/primitives').subtitle
  const title: typeof import('../components/primitives').title
  const trendCard: typeof import('../components/trend-card').default
  const updateReport: typeof import('../utils/mock-db').updateReport
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Generated, Timestamp, Record, Source, SqliteMaster, DB } from '../config/db.schema'
  import('../config/db.schema')
  // @ts-ignore
  export type { SiteConfig } from '../config/site'
  import('../config/site')
  // @ts-ignore
  export type { IconSvgProps } from '../components/icons'
  import('../components/icons')
  // @ts-ignore
  export type { IconMap, SourceIconProps } from '../components/source-icon'
  import('../components/source-icon')
  // @ts-ignore
  export type { DataSource, SourceItemProps } from '../components/source-item'
  import('../components/source-item')
  // @ts-ignore
  export type { ThemeSwitchProps } from '../components/theme-switch'
  import('../components/theme-switch')
  // @ts-ignore
  export type { InvokeCollectClickupParams, ClickupTask, InvokeCollectClickupResult } from '../services/invoke-collect-clickup'
  import('../services/invoke-collect-clickup')
  // @ts-ignore
  export type { InvokeCollectGitParams, GitCommit, FileDiff, InvokeCollectGitResult } from '../services/invoke-collect-git'
  import('../services/invoke-collect-git')
  // @ts-ignore
  export type { PostN8nApiKeyParams, PostN8nApiKeyResult } from '../services/post-n8n-api-key'
  import('../services/post-n8n-api-key')
  // @ts-ignore
  export type { PostN8nLoginParams } from '../services/post-n8n-login'
  import('../services/post-n8n-login')
  // @ts-ignore
  export type { PostN8nRegisterParams } from '../services/post-n8n-register'
  import('../services/post-n8n-register')
  // @ts-ignore
  export type { N8nNodeParameters, N8nNode, N8nConnectionItem, N8nConnections, N8nWorkflowSettings, N8nHomeProject, PostN8nWorkflowParams, PostN8nWorkflowResult } from '../services/post-n8n-workflow'
  import('../services/post-n8n-workflow')
  // @ts-ignore
  export type { RecordCreateInput } from '../services/sql-record-create'
  import('../services/sql-record-create')
  // @ts-ignore
  export type { RecordQueryInput } from '../services/sql-record-query'
  import('../services/sql-record-query')
  // @ts-ignore
  export type { RecordUpdateInput } from '../services/sql-record-update'
  import('../services/sql-record-update')
  // @ts-ignore
  export type { ReportCreateInput } from '../services/sql-report-create'
  import('../services/sql-report-create')
  // @ts-ignore
  export type { ReportSearchInput } from '../services/sql-report-query'
  import('../services/sql-report-query')
  // @ts-ignore
  export type { ReportUpdateInput } from '../services/sql-report-update'
  import('../services/sql-report-update')
  // @ts-ignore
  export type { SourceCreateInput } from '../services/sql-source-create'
  import('../services/sql-source-create')
  // @ts-ignore
  export type { SourceQueryInput } from '../services/sql-source-query'
  import('../services/sql-source-query')
  // @ts-ignore
  export type { Report, DatabaseItem, SourceType, SourceConfig } from '../utils/mock-db'
  import('../utils/mock-db')
}
