/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const AlimailIcon: typeof import('../components/icons').AlimailIcon
  const ClickupIcon: typeof import('../components/icons').ClickupIcon
  const CornerActions: typeof import('../components/corner-actions').CornerActions
  const Dialog: typeof import('../components/dialog').Dialog
  const Ellipsis: typeof import('../components/ellipsis').Ellipsis
  const Form: typeof import('../components/form').Form
  const FormControl: typeof import('../components/form').FormControl
  const FormDescription: typeof import('../components/form').FormDescription
  const FormField: typeof import('../components/form').FormField
  const FormItem: typeof import('../components/form').FormItem
  const FormLabel: typeof import('../components/form').FormLabel
  const FormMessage: typeof import('../components/form').FormMessage
  const Fragment: typeof import('react').Fragment
  const GitIcon: typeof import('../components/icons').GitIcon
  const GithubIcon: typeof import('../components/icons').GithubIcon
  const GmailIcon: typeof import('../components/icons').GmailIcon
  const Label: typeof import('../components/label').Label
  const Link: typeof import('react-router-dom').Link
  const Logo: typeof import('../components/icons').Logo
  const Modal: typeof import('../components/modal').Modal
  const Model: typeof import('../database/model').Model
  const MoonFilledIcon: typeof import('../components/icons').MoonFilledIcon
  const N8NIcon: typeof import('../components/icons').N8NIcon
  const N8N_API_URL: typeof import('../config/constants').N8N_API_URL
  const N8N_LOGIN_DATA: typeof import('../config/constants').N8N_LOGIN_DATA
  const N8N_REGISTER_DATA: typeof import('../config/constants').N8N_REGISTER_DATA
  const N8N_WEBHOOK_ID: typeof import('../config/constants').N8N_WEBHOOK_ID
  const NavLink: typeof import('react-router-dom').NavLink
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const ReportCountdown: typeof import('../components/report-countdown').ReportCountdown
  const ReportEditor: typeof import('../components/report-editor').ReportEditor
  const ReportGenerator: typeof import('../components/report-generator').ReportGenerator
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const SlackIcon: typeof import('../components/icons').SlackIcon
  const SourceFormClickup: typeof import('../components/souce-form-clickup').SourceFormClickup
  const SourceFormGit: typeof import('../components/souce-form-git').SourceFormGit
  const SourceIcon: typeof import('../components/source-icon').SourceIcon
  const SourceItem: typeof import('../components/source-item').SourceItem
  const SourceSelect: typeof import('../components/source-select').SourceSelect
  const StepDeepSeekApiKey: typeof import('../components/step-deepseek-api-key').StepDeepSeekApiKey
  const StepStatus: typeof import('../components/step-status').StepStatus
  const SunFilledIcon: typeof import('../components/icons').SunFilledIcon
  const Suspense: typeof import('react').Suspense
  const ThemeSwitch: typeof import('../components/theme-switch').ThemeSwitch
  const TrendCard: typeof import('../components/trend-card').TrendCard
  const UpdateStatus: typeof import('../components/update-status').UpdateStatus
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const cn: typeof import('../utils/utility').cn
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const dailyReportPrompt: typeof import('../config/prompts').dailyReportPrompt
  const db: typeof import('../database/index').db
  const forwardRef: typeof import('react').forwardRef
  const layouts: typeof import('../layouts/index').layouts
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const queryClient: typeof import('../config/client').queryClient
  const retry: typeof import('../utils/utility').retry
  const siteConfig: typeof import('../config/site').siteConfig
  const sourceOptions: typeof import('../config/options').sourceOptions
  const startTransition: typeof import('react').startTransition
  const storage: typeof import('../config/storage').storage
  const store: typeof import('../store/index').store
  const subtitle: typeof import('../components/primitives').subtitle
  const tauriStorageDriver: typeof import('../config/storage.driver').tauriStorageDriver
  const title: typeof import('../components/primitives').title
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useFormField: typeof import('../components/form').useFormField
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Model } from '../database/model'
  import('../database/model')
  // @ts-ignore
  export type { Generated, Timestamp, Record, Report, Source, Workspace, DB } from '../database/types'
  import('../database/types')
  // @ts-ignore
  export type { SiteConfig } from '../config/site'
  import('../config/site')
  // @ts-ignore
  export type { TauriStorageDriverOptions } from '../config/storage.driver'
  import('../config/storage.driver')
  // @ts-ignore
  export type { DialogProps } from '../components/dialog'
  import('../components/dialog')
  // @ts-ignore
  export type { EllipsisProps } from '../components/ellipsis'
  import('../components/ellipsis')
  // @ts-ignore
  export type { IconSvgProps } from '../components/icons'
  import('../components/icons')
  // @ts-ignore
  export type { ModalProps } from '../components/modal'
  import('../components/modal')
  // @ts-ignore
  export type { ReportEditorProps } from '../components/report-editor'
  import('../components/report-editor')
  // @ts-ignore
  export type { ReportGeneratorProps } from '../components/report-generator'
  import('../components/report-generator')
  // @ts-ignore
  export type { IconMap, SourceIconProps } from '../components/source-icon'
  import('../components/source-icon')
  // @ts-ignore
  export type { SourceItemProps } from '../components/source-item'
  import('../components/source-item')
  // @ts-ignore
  export type { SourceSelectProps } from '../components/source-select'
  import('../components/source-select')
  // @ts-ignore
  export type { ThemeSwitchProps } from '../components/theme-switch'
  import('../components/theme-switch')
  // @ts-ignore
  export type { RetryOptions } from '../utils/utility'
  import('../utils/utility')
}
