//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::record::Entity as Record;
pub use super::report::Entity as Report;
// pub use super::source::Entity as Source;
// pub use super::workflow::Entity as Workflow;
