//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "record")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(column_type = "custom(\"JSONB\")")]
    pub data: String,
    #[sea_orm(column_name = "createdAt", column_type = "custom(\"DATETIME\")")]
    pub created_at: String,
    #[sea_orm(column_name = "updatedAt", column_type = "custom(\"DATETIME\")")]
    pub updated_at: String,
    #[sea_orm(column_name = "sourceId")]
    pub source_id: i32,
    #[sea_orm(column_name = "workspaceId")]
    pub workspace_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::source::Entity",
        from = "Column::SourceId",
        to = "super::source::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Source,
    #[sea_orm(
        belongs_to = "super::workspace::Entity",
        from = "Column::WorkspaceId",
        to = "super::workspace::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Workspace,
}

impl Related<super::source::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Source.def()
    }
}

impl Related<super::workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
