export const presetProviders = {
  deepseek: {
    label: 'DeepSeek',
    protocol: 'openai',
    models: [
      { value: 'deepseek-chat', label: 'DeepSeek Chat' },
      { value: 'deepseek-coder', label: 'DeepSeek Coder' },
      { value: 'deepseek-reasoner', label: 'DeepSeek Reasoner' },
    ],
  },
  openai: {
    label: 'OpenAI',
    protocol: 'openai',
    models: [
      { value: 'chatgpt-4o-latest', label: 'ChatGPT 4o Latest' },
      { value: 'gpt-3.5-turbo', label: 'GPT-3.5 Turbo' },
      { value: 'gpt-4-turbo', label: 'GPT-4 Turbo' },
      { value: 'gpt-4.1-mini', label: 'GPT-4.1 Mini' },
      { value: 'gpt-4.1-nano', label: 'GPT-4.1 Nano' },
      { value: 'gpt-4.1', label: 'GPT-4.1' },
      { value: 'gpt-4', label: 'GPT-4' },
      { value: 'gpt-4o-mini', label: 'GPT-4o Mini' },
      { value: 'gpt-4o', label: 'GPT-4o' },
      { value: 'gpt-5.1', label: 'GPT-5.1' },
      { value: 'gpt-5.1-chat-latest', label: 'GPT-5.1 Chat Latest' },
      { value: 'gpt-5.1-codex-mini', label: 'GPT-5.1 Codex Mini' },
      { value: 'gpt-5.1-codex', label: 'GPT-5.1 Codex' },
      { value: 'gpt-5.1-codex-max', label: 'GPT-5.1 Codex Max' },
      { value: 'gpt-5.2', label: 'GPT-5.2' },
      { value: 'gpt-5.2-chat-latest', label: 'GPT-5.2 Chat Latest' },
      { value: 'gpt-5.2-pro', label: 'GPT-5.2 Pro' },
      { value: 'gpt-5-chat-latest', label: 'GPT-5 Chat Latest' },
      { value: 'gpt-5-codex', label: 'GPT-5 Codex' },
      { value: 'gpt-5-mini', label: 'GPT-5 Mini' },
      { value: 'gpt-5-nano', label: 'GPT-5 Nano' },
      { value: 'gpt-5-pro', label: 'GPT-5 Pro' },
      { value: 'gpt-5', label: 'GPT-5' },
      { value: 'o1', label: 'O1' },
      { value: 'o3-mini', label: 'O3 Mini' },
      { value: 'o3', label: 'O3' },
    ],
  },
  anthropic: {
    label: 'Anthropic',
    protocol: 'anthropic',
    models: [
      { value: 'claude-3-5-sonnet-20241022', label: 'Claude 3.5 Sonnet' },
      { value: 'claude-3-5-haiku-20241022', label: 'Claude 3.5 Haiku' },
      { value: 'claude-3-opus-20240229', label: 'Claude 3 Opus' },
      { value: 'claude-haiku-4-5', label: 'Claude Haiku 4.5' },
      { value: 'claude-opus-4-0', label: 'Claude Opus 4.0' },
      { value: 'claude-opus-4-1', label: 'Claude Opus 4.1' },
      { value: 'claude-opus-4-5', label: 'Claude Opus 4.5' },
      { value: 'claude-sonnet-4-0', label: 'Claude Sonnet 4.0' },
      { value: 'claude-sonnet-4-5', label: 'Claude Sonnet 4.5' },
      { value: 'claude-sonnet-4-6', label: 'Claude Sonnet 4.6' },
      { value: 'claude-opus-4-6', label: 'Claude Opus 4.6' },
    ],
  },
  google: {
    label: 'Google',
    protocol: 'google',
    models: [
      { value: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
      { value: 'gemini-2.0-flash-001', label: 'Gemini 2.0 Flash 001' },
      { value: 'gemini-2.0-flash-lite', label: 'Gemini 2.0 Flash Lite' },
      { value: 'gemini-2.0-flash-lite-001', label: 'Gemini 2.0 Flash Lite 001' },
      { value: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
      { value: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
      { value: 'gemini-2.5-flash-image', label: 'Gemini 2.5 Flash Image' },
      { value: 'gemini-2.5-flash-lite', label: 'Gemini 2.5 Flash Lite' },
      { value: 'gemini-2.5-flash-lite-preview-09-2025', label: 'Gemini 2.5 Flash Lite Preview 09 2025' },
      { value: 'gemini-2.5-flash-preview-tts', label: 'Gemini 2.5 Flash Preview TTS' },
      { value: 'gemini-2.5-pro-preview-tts', label: 'Gemini 2.5 Pro Preview TTS' },
      { value: 'gemini-2.5-flash-native-audio-latest', label: 'Gemini 2.5 Flash Native Audio Latest' },
      { value: 'gemini-2.5-flash-native-audio-preview-09-2025', label: 'Gemini 2.5 Flash Native Audio Preview 09 2025' },
      { value: 'gemini-2.5-flash-native-audio-preview-12-2025', label: 'Gemini 2.5 Flash Native Audio Preview 12 2025' },
      { value: 'gemini-2.5-computer-use-preview-10-2025', label: 'Gemini 2.5 Computer Use Preview 10 2025' },
      { value: 'gemini-3-pro-preview', label: 'Gemini 3 Pro Preview' },
      { value: 'gemini-3-pro-image-preview', label: 'Gemini 3 Pro Image Preview' },
      { value: 'gemini-3-flash-preview', label: 'Gemini 3 Flash Preview' },
      { value: 'gemini-3.1-pro-preview', label: 'Gemini 3.1 Pro Preview' },
      { value: 'gemini-3.1-pro-preview-customtools', label: 'Gemini 3.1 Pro Preview Customtools' },
      { value: 'gemini-3.1-flash-image-preview', label: 'Gemini 3.1 Flash Image Preview' },
      { value: 'gemini-3.1-flash-lite-preview', label: 'Gemini 3.1 Flash Lite Preview' },
      { value: 'gemini-pro-latest', label: 'Gemini Pro Latest' },
      { value: 'gemini-flash-latest', label: 'Gemini Flash Latest' },
      { value: 'gemini-flash-lite-latest', label: 'Gemini Flash Lite Latest' },
      { value: 'deep-research-pro-preview-12-2025', label: 'Deep Research Pro Preview 12 2025' },
      { value: 'nano-banana-pro-preview', label: 'Nano Banana Pro Preview' },
      { value: 'aqa', label: 'AQA' },
      { value: 'gemini-robotics-er-1.5-preview', label: 'Gemini Robotics ER 1.5 Preview' },
      { value: 'gemma-3-1b-it', label: 'Gemma 3 1B IT' },
      { value: 'gemma-3-4b-it', label: 'Gemma 3 4B IT' },
      { value: 'gemma-3n-e4b-it', label: 'Gemma 3N E4B IT' },
      { value: 'gemma-3n-e2b-it', label: 'Gemma 3N E2B IT' },
      { value: 'gemma-3-12b-it', label: 'Gemma 3 12B IT' },
      { value: 'gemma-3-27b-it', label: 'Gemma 3 27B IT' },
    ],
  },
  custom: undefined,
} as const
