//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

#[allow(unused_imports)]
pub use super::record::Entity as Record;
// pub use super::report::Entity as Report;
// pub use super::source::Entity as Source;
