//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

#![allow(dead_code)]

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "record")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(column_type = "custom(\"JSONB\")")]
    pub data: String,
    #[sea_orm(column_name = "createdAt", column_type = "Integer")]
    pub created_at: i64,
    #[sea_orm(column_name = "updatedAt", column_type = "Integer")]
    pub updated_at: i64,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text")]
    pub tool: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
